### PR TITLE
added 2 methods: Transform.multiply4x4Many() & Transform.multiplyMany()

### PR DESCRIPTION
**Pull request by rajnathani**
```
Transform.multiplty(Transform.multiply(m1, m2), m3)
```

becomes

```
Transform.multiplyMany([m1, m2, m3])
```

Following the same convention is `Transform.multiply4x4Many()`

### CODE REVIEW

**Comment by rajnathani** [comment]
The documentation for `Transform.multiplty()` and `Transform.multiply4x4()` currently state that

> Multiply two or more Transform matrix...

This doesn't hold true in the implementation.

**Comment by rajnathani** [comment]
To maintain backwards compatibility `Transform.multiplty()` and `Transform.multiply4x4()` cannot be altered.
The possibility of overloading the above functions through type checking is out of the question because [m1, m2, m3] is an array, but so are m1, m2 and m3 individually,

**Comment by dmvaldman** [comment]
We are considering how to provide this convenience method. Due to performance requirements, multiplying matrices needs to be highly optimized and JITable. Having a variable number of arguments breaks the ability to do JIT compilation. Any such modification needs to be validated via jsPerf.

**Comment by rajnathani** [comment]
Alright I created a test here: [http://jsperf.com/jit-matrix-multiplication-many](http://jsperf.com/jit-matrix-multiplication-many)  
Note that for performance reasons I had to modify the code (relative to the push req) for `multiplyMany()` to not call `multiply()`, but instead to embed the calculation within the loop to save on callbacks.
The tests are rather cutthroat right now, in some cases using an array outperformances using callbacks, in other cases the opposite.

**Comment by rajnathani** [comment]
update: on chrome callbacks win, on firefox arrays win, the important thing to note is that the margin of defeat in firefox is relatively lesser compared to that of on chrome.

**Comment by dmvaldman** [comment]
Thanks for making the test! I'm testing over here as well. Another thing to note is that your test has the same number of variables arguments passed in each time. The JIT compilation is heavily dependent on having consistent arguments passed in, so it will effectively JIT even for a variable argument list as long as it keeps getting the same number of arguments. I have a simple version to test:

http://jsperf.com/jit-matrix-multiplication-many/2

**Comment by dmvaldman** [comment]
Pretty weird that Firefox is actually better in this case! Boggles the mind.

**Comment by rajnathani** [comment]
Okay. It seems like for now only SpiderMonkey works faster with arrays.
We got to test IE still, I'm on a mac, do you have access to IE?

**Comment by andrewdeandrade** [comment]
FWIW I was under the impression that benchmark.js that jsperf is based on specifically uses techniques to avoid allowing JIT to take place since they want to get a statistically valid number. For example, if I'm testing a function that realistically only gets run a few times (i.e. never gets "hot") then allowing JITting to happen ruins my benchmarking.

**Pull request closed without merging**
