### PR TITLE
Remove duplicate scripts content in package.json

### PR DESCRIPTION
**Pull request by thaiat**
There was a duplicate in the package.json "scripts"

### CODE REVIEW

**Comment by dmvaldman** [comment]
@malandrew @TheAlphaNerd Can you comment?

**Comment by MylesBorins** [comment]
All is well.. this can be pulled

**Comment by dmvaldman** [comment]
Approved. @TheAlphaNerd

**Comment by MylesBorins** [comment]
Merged into Internal.  Expect to see this live very very soon
:+1:

**Pull request closed without merging**
