### PR TITLE
Add the "align" modifier property to Scene.js

### PR DESCRIPTION
**Pull request by markmarijnissen**
Scene.js was not updated to use the new "align" property of Modifiers. Not it is!

### CODE REVIEW

**Comment by michaelobriena** [comment]
Thanks for this.   Should see this in the next release.

**Comment by dmvaldman** [comment]
@ftripier

**Comment by dmvaldman** [comment]
Approved @TheAlphaNerd

**Comment by MylesBorins** [comment]
Merged on Internal, expect to see it on public really soon!

**Pull request closed without merging**
