### PR TITLE
fixes GH-8

### PR DESCRIPTION
**Pull request by fwienber**
Reuse `object.on` (bound!) for `object.addListener` instead of unbound `handler.on`.

### CODE REVIEW

**Comment by fwienber** [comment]
Unfortunately, it seems I cannot reach your [CLA page](https://famo.us/legal/cla.html)...

**Comment by dmvaldman** [comment]
Thanks for the fix! We're working the CLA stuff now and will let you know very soon. Then we'll merge in your request. Thanks for your patience!

**Comment by dmvaldman** [comment]
@fwienber  IT IS HERE!!!!! https://famo.us/cla/individual

thank you so much for your patience!

**Comment by dmvaldman** [comment]
Gentle reminder @fwienber to sign out CLA if you could!

**Comment by fwienber** [comment]
Ah yes. Problem is, I would need a company CLA, not an individual CLA, as I work on Web UIs as an employee, so my employer has to agree that I contribute to famo.us (and certainly would do so, but does not allow me to sign an individual CLA).

**Comment by dmvaldman** [comment]
@malandrew What needs to happen for us to also have a company CLA?

**Comment by andrewdeandrade** [comment]
The API already supports a company CLA, we just need to add the form and front end validation to the website. 

@timjchin When do you think we'll be able to add the corporate CLA to the website?

**Comment by dmvaldman** [comment]
Hey @fwienber, sorry for the hold up on our side. I've taken the liberty of fixing this internally for now and it will be merged into our next release. Thanks!

**Pull request closed without merging**
