### PR TITLE
Surface.emit should check event before doing event.stopPropogation

### PR DESCRIPTION
**Pull request by zgardner**
I expected emit to allow just a type to be passed.
This is common in other frameworks that have eventing (e.g. ExtJS) where the event can be "the message" without any payload.

The first conditional in this method does if (event && ...)
The second conditional does if (handled && event.stopPropogation)
To support just passing type, it should be if(handled && event && event.stopPropogation).

### CODE REVIEW

**Comment by andrewdeandrade** [comment]
@zgardner This may be a deliberate design decision. There are a few ways in which we handle events differently than other frameworks for performance reasons. In the meantime, make sure to go through the events guide: http://famo.us/guides/dev/events.html

Will ping the principle engineers responsible for the event system so they can chime in on this. 

Calling @marklu and @dmvaldman

**Comment by zgardner** [comment]
Thanks for the quick response.
It seems weird the first conditional checks event && if the param is required.

**Comment by zgardner** [comment]
Any ideas on this @marklu and @dmvaldman?

**Comment by dmvaldman** [comment]
Sorry for the slow response on my end. Can you give a use case for a surface emitting a custom event? Typically surfaces listen to events, like `click` but do not emit events; that responsibility is for a higher level view or widget. Happy to include your desired functionality if you provide a use case.

**Comment by zgardner** [comment]
I built a guitar tuner, and the strings are surfaces. It listens for click, and passed on the message to the controller. If the controller decides to actually play that string, it sends a "pluck" event. The surface can then react accordingly.

Even if custom events are not directly supported, it is inconsistent to say event is required, have the second conditional assume it is required, but the first conditional do event &&.

**Comment by dmvaldman** [comment]
Happy to merge in this change once our CLA stuff gets through. Thanks!

**Comment by dmvaldman** [comment]
@zgardner IT IS HERE!!!!! https://famo.us/cla/individual

thank you so much for your patience!

**Comment by zgardner** [comment]
Signed. Thanks @dmvaldman

**Pull request merged**
