### PR TITLE
Added "visibleFrom" to Modifier

### PR DESCRIPTION
**Pull request by markmarijnissen**
How to manipulate visibility?
- Write custom .render() function in a view or component
- Use a RenderController - does complicated stuff to track transitions in and out
- Use a Scrollview - does complicated stuff to only render what is visible

What about simply showing/hiding things? Use cases
- Popups or notifications (without animations)
- Pages in a simple website
- Basically every use case for render controller without animations.

I've added a `visibleFrom` method and a `_visible` flag. RenderSpec will be `null` if visible is `false`.

### CODE REVIEW

**Comment by dmvaldman** [comment]
Have you considered setting `myModifier.opacityFrom(0)`? This will not stop events from being captured, however, which your returning `null` will do. Keep in mind that returning `null` will effectively clean up all the contents of the HTML (incurring a costly DOM touch). When visibility is reset to `true`, Famo.us will find an unused DOM node and repopulate it (incurring a second DOM touch).

It turns out "removing" something is a complicated topic if you want to minimize DOM interaction, which is the reason for the complexity of adding a `RenderController`. Happy to keep this discussion going and see if we can mitigate your use case in a way that doesn't degrade performance.

**Comment by markmarijnissen** [comment]
Yes, for some use-cases it might be OK to have zero opacity; but semantically this is different than what I intend to do: I just want to show/hide elements to manipulate a rendering tree. Of course semantics can be in an abstraction layer on top of the core components.

I did not realize the possible performance penalty for this. As an alternative, I might set opacity to 0 and z-index the surface way back. (This way, it is also invisible for events - i.e. imagine a popup-surface that after disappearing still captures touch events).

So proper place for this might be to create a VisibilityModifier that toggles Z-translate and opacity.

What about setting CSS property to display: none? Would this also cost a performance penalty (as basically setting opacity is also CSS).

Speaking about performance: Are there tools to measure? (jsperf.com? chrome tools?)

**Comment by dcsan** [comment]
in terms of a performance hit, isn't that just at the single frame when the item gets removed from the DOM? if you have an item suddenly disappear its usually not in the middle of an animation, so a stutter would not be noticeable. 

in the case where there is for example a separate animation in the background, its a slightly different case, but that's probably a much less frequent use case, and we may have to be using layers of famous renderNodes etc to deal with it.

by leaving a bunch of items in the scene with opacity=X - isn't that a huge perf. hit? are the browsers smart enough to know that somewhere an opacity=0  so there's no need to calculate/render any part of that tree. overlaid transparent  items also have huge potential for rendering overhead.

additionally is there a way to get a JQuery handle to a famous surface? so if we don't want to deal with the complication of your API, and there is no performance penalty, we can just do 

`$("#famousThing").hide();`

i realize we can insert an ID'd div into a famous surface, but what if we want to cull stuff out at the surface itself point, and not leave a bunch of dangling empty surfaces?

**Comment by markmarijnissen** [comment]
@dcsan No, it is not just a single frame: The browser needs to destroy & create DOM-nodes, which are costly especially in terms of memory. I am guessing the DOM-node pooling is one of the clever things famo.us does to keep memory usage low and prevent memory leaks. I am guessing that when memory gets low, an allocation can take more time than 16 ms, causing a drop in performance (FPS). Can somebody confirm or reject my speculation?

**Comment by dcsan** [comment]
right but there are many cases in a site where you want to hide/show an element, that are not animation dependent. eg I think famous will be used for transitions and places you used to see Flash on websites - on splash pages/menus etc. 
But if you want to simply show a popup toast alert, or tooltip... being able to show/hide things easily would be good. if nothing else is moving you won't notice a stutter no matter how long it takes.

right now its hard to mix and match famous with normal DOM manipulation (see how touchMove events disappear) so a leaner API would be a huge benefit.

separate issue but related - transitions - which means creating 3 different elements (modifier, node, graph) to just position or move something. compared to  http://ricostacruz.com/jquery.transit/
    `$('.box').transition({ x: 40, y: 40 });`
which also begets CSS smooth animation

**Comment by dcsan** [comment]
> you only use famo.us for the animated components

yes in theory, when things that prevent that are fixed, eg:
https://github.com/Famous/core/issues/14

**Comment by kof** [comment]
I also wonder what is the reason for memory usage increase. Is it the references to dom nodes? Does memory increases if references to dom nodes handled properly? Need to do some research and bench.

**Comment by kof** [comment]
Also the question is if the memory usage increases only when dom nodes has been inserted into the render tree  or already when creating dom nodes without to render.

**Comment by dmvaldman** [comment]
Closing as `RenderController` is the supported way of having this functionality

**Pull request closed without merging**
