### PR TITLE
`definition` can be an array, too (see: `_parseArray()`).

### PR DESCRIPTION
**Pull request by jonathanmarvens**

### CODE REVIEW

**Comment by dmvaldman** [comment]
The correct type is a Famo.us `Spec` which we'll need to define. Thanks for pointing out.

**Comment by jonathanmarvens** [comment]
Ah, okay ... good to know. BTW, I see this in several parts of the Famous codebase (where the documentation isn't complete). Is it okay and worth it to continue fixing them and opening PRs, or are y'all aware of those, too?

Thanks!

\- Jonathan

**Comment by dmvaldman** [comment]
We're away but always appreciate the help!

**Comment by michaelobriena** [comment]
@jonathanmarvens keep open or do you want to change to the proper type?

**Comment by MylesBorins** [comment]
@michaelobriena @jonathanmarvens what is the current state of this?

**Comment by MylesBorins** [comment]
hey @jonathanmarvens can you move this to famous/famous referencing this issue?

**Comment by jonathanmarvens** [comment]
Hey, folks.

Sorry for disappearing on y'all like that.

@TheAlphaNerd So I should just reopen the same issue on there?

\- Jonathan

**Comment by MylesBorins** [comment]
jonathan indeed!

**Comment by MylesBorins** [comment]
@michaelobriena can you close this?

**Pull request closed without merging**
