### PR TITLE
Simplified some code.

### PR DESCRIPTION
**Pull request by jonathanmarvens**
Code like this, while shorter, is somewhat unreadable (at least for a few seconds), so I simplified it.

Thanks!

\- Jonathan

### CODE REVIEW

**Comment by dmvaldman** [comment]
Goin deep! We'll take a look. We usually like jsPerf tests when evaluating checks like these if you don't mind linking to one.

**Comment by jonathanmarvens** [comment]
@dmvaldman Is a jsPerf really necessary for this modification? In pretty much any modern JavaScript interpreter, except for loading property `_object` from `this` 2x @ https://github.com/jonathanmarvens/famous-core/blob/d5b9fa6753dc797e8b905aec91ad594d0962e703/RenderNode.js#L68, the original code and my minimally modified version should have [almost, if not exactly] equivalent representations ... with inline caching and other fancy optimizations in the interpreters, there should be absolutely no difference in performance for this tiny modification (that would be an interpreter bug). I'm okay with doing a jsPerf benchmark if it's really necessary, though.

Thanks!

\- Jonathan

**Comment by AdrianRossouw** [comment]
their project, their rules. they have a lot more browsers to worry about than you might think (like all the mobile ones)

although this seems like the kind of thing that can be automated.

**Comment by jonathanmarvens** [comment]
Guys, I apologize if I sounded rude or condescending in that last reply ... wasn't my intention. @Vertice I agree with you. @dmvaldman I'll get some jsPerf tests done for this and come back here with the link.

Thanks!

\- Jonathan

**Comment by michaelobriena** [comment]
@jonathanmarvens 

I ran some perfs and it looks like the ternary is pretty optimized.  I was getting faster speeds for the current code.  Feel free to keep investigating but right now I would say the switch is not a good move.

http://jsperf.com/rendernode-get

**Comment by dmvaldman** [comment]
Thanks for checking @michaelobriena

**Pull request closed without merging**
