### PR TITLE
fixes issue #18

### PR DESCRIPTION
**Pull request by raix**
I've experienced that Surface fails due to the webkit transform test at
https://github.com/Famous/core/blob/master/Surface.js#L15 - This is the
case when loading scripts before body is created.

We could change it to something like:

``` js
var usePrefix = document.createElement('div').style.webkitTransform !==
undefined;
```

### CODE REVIEW

**Comment by dmvaldman** [comment]
You are correct. We're waiting for the CLA to be signed of the original contributor of this bug to merge this fix in.

**Comment by raix** [comment]
@dmvaldman I'm sorry - where do I sign?

**Comment by dmvaldman** [comment]
Eek, I think I replied to the wrong message :-/

We'll consider this fix and get back to you soon. We'll have a CLA for your to sign if we accept the pull request. Thanks!

**Comment by dmvaldman** [comment]
Fixed, thank you! This will be in the next release of famous.git

**Pull request merged**
