### PR TITLE
Fix EventHandler.pipe/unpipe

### PR DESCRIPTION
**Pull request by the-reality-engineer**
In reference to https://github.com/Famous/famous/issues/88

### CODE REVIEW

**Comment by dmvaldman** [comment]
We opt to use the `subscribe` pattern over the `pipe` pattern for performance reasons. There is a subtle difference.

If `WidgetA` emits many events, and pipes to `WidgetB`. `WidgetB` will receive those events regardless of whether it does anything to them. `Subscribe` gets around this by going the other direction. `WidgetB` explicitly requests events from `WidgetA` with `subscribe`, instead of listening to all piped events.

**Comment by the-reality-engineer** [comment]
I do understand that subscribe behavior is preferred because it is more performant, but what you just described as the pipe behavior (and what the documentation describes as the pipe behavior) is not in actuality the current "pipe" behavior. 

> If WidgetA emits many events, and pipes to WidgetB. WidgetB will receive those events regardless of whether it does anything to them.

In other words, your statement here is simply not true, not according to the current implementation. Right now, if WidgetA emits many events and pipes to WidgetB, and WidgetB does nothing, WidgetB will NOT receive those events.

**Comment by the-reality-engineer** [comment]
FYI, this is the use-case I'm addressing here.

The following code prints 'type:hi' successfully:

``` javascript
var x = new EventHandler()
var y = new EventMapper(function(type, event) {
  console.log('type:' + type)
  return someEventHandler
})
x.pipe(y)

x.trigger('hi')
```

The following code does not. 

``` javascript
var x = new EventHandler()
var y = new EventHandler()
var z = new EventMapper(function(type, event) {
  console.log('type:' + type)
  return someEventHandler
})
x.pipe(y)
y.pipe(z)

x.trigger('hi')
```

Ideally (and intuitively) both should work...

**Comment by dmvaldman** [comment]
I think this is a bug. Your pull request of removing subscribe isn't the correct fix, but we'll take a closer look at the issue. Thanks!

**Comment by the-reality-engineer** [comment]
Thanks for taking a look!

**Comment by dmvaldman** [comment]
@DnMllr can you take a look

**Comment by the-reality-engineer** [comment]
@dmvaldman Btw, the current event guide (http://famo.us/guides/events) suggests that developers have the option to choose between a piping model and a subscribing model. It also encourages developers to choose the subscribing model. In reality, this is misleading, because there is no option to use a piping model since the `pipe` function discretely uses a subscribe model. 

```
Piping vs Subscribing

When listening on DOM events, a subscribe pattern is more performant
because you can subscribe to only the events you need. In a piping model, all
events must be broadcast (even if they are never used) in order to listen to them downstream.
Hence, you should subscribe from Surfaces, the Engine (which can both listen to the DOM),
whereas you should pipe to (or subscribe from) custom events broadcast from widgets.
```

So, at some point, it's clear that the intent was to allow developers to choose between a true piping model and a true subscribing model, with encouragement to use subscribing where possible, but this decision was seemingly reversed. The documentation even gives examples of how using the `pipe` or `subscribe` function will/won't work in certain situations, however this documentation is all incorrect, since they both rely on the same underlying subscribe model. For example:

``` js
//Note: piping from a Engine or Surface does nothing unless they have subscribed to the event!

    surface.pipe(widgetA);
    widgetA.on('touchmove', function(event){...}); // does nothing. Surface is not yet emitting 'touchmove'

    widgetA.subscribe(surface);
    widgetA.on('touchmove', function(event){...}); // works!
```

Actually, both of the above statements currently work (assuming that the following line of missing code is implied:  `widgetA.eventInput.pipe(widgetA.eventOutput)`, otherwise they would both "do nothing")

I just wanted to bring this to your attention, because this documentation is currently misleading, and was one of the reasons why I considered the `pipe` function using `subscribe` to be a bug.

**Comment by dmvaldman** [comment]
thanks for the detailed explanation. @DnMllr take a look please

**Comment by DnMllr** [comment]
@speigg You're right that something is wrong here, though, I don't interpret that section from our guide on events as cleanly as you do. I think we're always going to try and find the most optimized pattern in all situations (such as preferring subscribe over pipe if the classes allow the opportunity), and so I read that section in the guide as justifying that point of view.

Regardless of interpretive differences over our documentation, our current implementation of subscribing and piping has a significant error in implementation, which your examples point out rather cleanly. I think it is unlikely that we will remove pipe delegating to subscribe if possible, but my current thinking is that subscribe will no longer pass the responsibility of responding to events upstream. This will be a fairly major change and so it might not happen immediately, but it will happen soon. Thank you for bringing this to our attention.

**Comment by the-reality-engineer** [comment]
@DnMllr I think the documentation would be clearer if it said what you just said more explicitly. But, aside from our interpretive differences, the widget example from the guide is still incorrect (saying that the pipe function will not work, while the subscribe function does, is incorrect). 

Yeah, it sounds like the solution will be somewhat complex. I don't think changing the subscribe implementation alone will work. For example, an event handler that pipes directly to an EventMapper (or any event handler that doesn't have a subscribe method), will need to notify all of it's upstream event handlers to pipe directly to that EventMapper. And when any event handler in the chain is unpiped from that chain, somehow the reverse needs to happen when the EventMapper is no longer in the chain. I think each EventHandler will have to keep a count on the number of times an EventMapper (or any non-subscribing handler) appears in it's downstream, and will need to unpipe only when that count reaches 0.

**Comment by MylesBorins** [comment]
hey @speigg can you move this to famous/famous referencing this issue?

**Comment by MylesBorins** [comment]
Moved to famous/famous#155

**Pull request closed without merging**
