### PR TITLE
Added support for Transform literals (used code from Scene.js)

### PR DESCRIPTION
**Pull request by IjzerenHein**

### CODE REVIEW

**Comment by dmvaldman** [comment]
How would you expect this to be used? Likely `Transform` will soon no longer be a dependency of `Modifier` as it will be a "shell" to add things into, like `RenderNode`

**Comment by markmarijnissen** [comment]
So what @dmvaldman is proposing is a chainable syntax? (like `add` from RenderNode).

```
    t = Transform().scale(1,0).translate(100,0):
```

And wat @IjzerenHein is proposing is a JSON definition syntax (taken from Scene.js) like:

```
    t = Transform.parse([{scale: [1,0]},{translate:[100,0,0]}])
```

With the added little trick that this JSON definition can also be used directly with modifiers.

**Comment by AdrianRossouw** [comment]
@markmarijnissen @dmvaldman @IjzerenHein  i would highly highly recommend we build the chainable syntax, and add the declarative syntax as optional sugar on top of it.

I learnt the hard way that you should use a turing complete language to drive stuff like this, otherwise you end up re-inventing the host language in the [inner platform effect](http://en.wikipedia.org/wiki/Inner-platform_effect)

There are just some things you can't say using arrays/objects, they simply aren't expressive enough, unless you turn them into something that looks like lisp.

**Comment by IjzerenHein** [comment]
David, my primary goal was to make it easier to do transforms. By having to write less code and making it easier to read (and being able to spot errors faster..). 
I really like the idea of chaining as suggested by Mark and Adrian. I fully support Adrians idea on adding a chainable syntax first, and if useful add literals later.

**Comment by markmarijnissen** [comment]
I'm curious to see where this goes. I am not sure I understand @dmvaldman correctly. Will `Transform` be a subclass of `RenderNode`? Will it be like a `ModifierChain`? (Which seems to me as a redundant class - especially when the rendering loop gets dirty flags, because then it wouldn't even help performance by saving commit calls)

**Comment by dmvaldman** [comment]
What I mean is that `Modifier` will not know about its contents. It shouldn't know about `Transform`, for instance. All it is responsible for is applying whatever happens to be its contents to the nodes below it in the render tree. This is the distinction between `StateModifier` (which knows about all its contents) and `Modifier`. Its contents could surely be chained, where it looks something like:

```
myModifier.add(sizeFrom).add(originFrom).add(transformFrom).add(GLShaderFrom).add(pointLightFrom)...
```

I hope this gives a sense of where we're going. `Modifier` as it is will be crushed by the complexity of all that it can take in if it proceeds on its current path. 

I like your ideas about chaining `Transform` methods as well :-)

**Comment by MylesBorins** [comment]
hey @IjzerenHein can you move this to famous/famous referencing this issue?

**Comment by MylesBorins** [comment]
ping @IjzerenHein

**Comment by IjzerenHein** [comment]
@TheAlphaNerd yeah I'll move it, too busy right now, probably next week

**Comment by MylesBorins** [comment]
@michaelobriena can you close this?

**Pull request closed without merging**
